### ISSUE TITLE
Add margins to imgs

### ISSUE THREAD

**Issue by bdm4** [CaseWesternReserveUniversity/CaseTemplates#136]

**Comment by bdm4** [comment]
3px 0 3px 3px?

**Comment by riverwaters** [comment]
Well - If an image is ever floated left it will need it on the right as
well.  I'm not sure if your content has that anywhere.

I'd probably do at least 5px.

On Wed, Dec 2, 2015 at 11:48 AM, Ben Margevicius <notifications@github.com>
wrote:

> 3px 0 3px 3px?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CaseWesternReserveUniversity/CaseTemplates/issues/136#issuecomment-161361308>
> .
>



-- 
*Jessica Becker*
Senior Director of Web Design and Development
University Marketing and Communications
Case Western Reserve University
Adelbert Hall, Suite 14
10900 Euclid Ave.
Cleveland, OH 44106-7017
Phone: 216-368-0603
